buildscript {
	ext {
		springBootVersion = '3.1.5'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

plugins {
	id 'java'
	id 'eclipse'
	id 'application'
	id 'org.springframework.boot' version '3.1.5'
	id 'io.spring.dependency-management' version '1.1.3'
	id 'com.diffplug.spotless' version '6.23.0'
}

jar {
	archiveBaseName = 'pressing-management'
	version = '0.0.1-SNAPSHOT'
}
// Use Java 21 as the project language level and prefer Gradle Java toolchains
sourceCompatibility = 21
targetCompatibility = 21

// Configure the Java toolchain to request a Java 21 JDK for compilation and runtime tasks
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	
	spotless {
	    java {
	        target 'src/**/*.java'
	        googleJavaFormat()
	        trimTrailingWhitespace()
	        endWithNewline()
	    }
	}
}


// Ensure the compiler targets Java 21 bytecode where possible
tasks.withType(JavaCompile) {
	options.release = 21
}

repositories {
	mavenCentral()
}


dependencies {
	implementation('org.springframework.boot:spring-boot-starter-actuator')
	implementation('org.springframework.boot:spring-boot-starter-data-jpa')
	implementation('org.postgresql:postgresql')
	implementation("org.flywaydb:flyway-core")
	implementation('org.springframework.boot:spring-boot-starter-security')
	implementation('org.springframework.boot:spring-boot-starter-aop')
	implementation('org.springframework.boot:spring-boot-starter-web')
	compileOnly('org.projectlombok:lombok')
	annotationProcessor('org.projectlombok:lombok')
	testImplementation('org.springframework.boot:spring-boot-starter-test')
	testImplementation('org.springframework.security:spring-security-test')
}
