spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pressing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/master
flyway:
  url: jdbc:postgresql://localhost:5432/pressing
  user: postgres
  password: postgres
  locations: classpath:db/migration

springdoc:
  swagger-ui:
    oauth:
      client-id: pressing-api
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://localhost:8082/swagger-ui/oauth2-redirect.html